import { EngineActivity, ProjectCalendar } from "../types/programmeEngine";
import { DEFAULT_CALENDARS } from "./cpmEngine";

export const SAMPLE_PROJECT_CONTROLS_ACTIVITIES: EngineActivity[] = [
  // 1.0 MILESTONES & ENABLING WORKS
  {
    id: "act-001",
    wbsCode: "M-010",
    name: "Notice to Proceed (NTP) & Site Possession",
    activityType: "StartMilestone",
    calendarId: "cal-5day",
    sortOrder: 1,
    originalDuration: 0,
    remainingDuration: 0,
    actualDuration: 0,
    progress: 100,
    status: "Complete",
    actualStart: "2026-02-01",
    actualFinish: "2026-02-01",
    constraintType: "MSO",
    constraintDate: "2026-02-01",
    predecessors: [],
    successors: [],
    baseline0: { baselineStart: "2026-02-01", baselineFinish: "2026-02-01", duration: 0 },
    baseline1: { baselineStart: "2026-02-01", baselineFinish: "2026-02-01", duration: 0 },
    earlyStart: "2026-02-01",
    earlyFinish: "2026-02-01",
    lateStart: "2026-02-01",
    lateFinish: "2026-02-01",
    totalFloat: 0,
    freeFloat: 0,
    isCritical: true,
    forecastStart: "2026-02-01",
    forecastFinish: "2026-02-01",
    varianceB0Days: 0,
    varianceB1Days: 0,
    responsiblePerson: "Employer / Engineer"
  },
  {
    id: "act-101",
    wbsCode: "ACT-101",
    name: "Site Establishment, Hoarding & Security Perimeter",
    description: "Installation of 2.4m anti-climb boundary hoarding, site offices, power & water connections",
    activityType: "Task",
    calendarId: "cal-6day",
    sortOrder: 2,
    originalDuration: 18,
    remainingDuration: 0,
    actualDuration: 18,
    progress: 100,
    status: "Complete",
    actualStart: "2026-02-02",
    actualFinish: "2026-02-21",
    constraintType: "ASAP",
    predecessors: [
      { id: "p-101-1", predecessorId: "act-001", type: "FS", lag: 0 }
    ],
    successors: [],
    baseline0: { baselineStart: "2026-02-02", baselineFinish: "2026-02-21", duration: 18, scopeQty: 850 },
    baseline1: { baselineStart: "2026-02-02", baselineFinish: "2026-02-21", duration: 18, scopeQty: 850 },
    resourceAssignment: {
      resourceId: "res-site",
      resourceName: "Enabling Works Crew",
      totalScopeQty: 850,
      unit: "lin.m",
      targetDailyRate: 50,
      actualDailyRateAchieved: 52
    },
    earlyStart: "2026-02-02",
    earlyFinish: "2026-02-21",
    lateStart: "2026-02-02",
    lateFinish: "2026-02-21",
    totalFloat: 4,
    freeFloat: 4,
    isCritical: false,
    forecastStart: "2026-02-02",
    forecastFinish: "2026-02-21",
    varianceB0Days: 0,
    varianceB1Days: 0,
    responsiblePerson: "Main Contractor"
  },
  {
    id: "act-102",
    wbsCode: "ACT-102",
    name: "Topographical Survey Grid & Geotechnical Probe Testing",
    description: "Precise benchmark leveling, CPT soundings, and borehole verification across piers P1-P8",
    activityType: "Task",
    calendarId: "cal-6day",
    sortOrder: 3,
    originalDuration: 12,
    remainingDuration: 0,
    actualDuration: 12,
    progress: 100,
    status: "Complete",
    actualStart: "2026-02-02",
    actualFinish: "2026-02-14",
    constraintType: "ASAP",
    predecessors: [
      { id: "p-102-1", predecessorId: "act-001", type: "FS", lag: 0 }
    ],
    successors: [],
    baseline0: { baselineStart: "2026-02-02", baselineFinish: "2026-02-14", duration: 12, scopeQty: 24 },
    baseline1: { baselineStart: "2026-02-02", baselineFinish: "2026-02-14", duration: 12, scopeQty: 24 },
    resourceAssignment: {
      resourceId: "res-geotech",
      resourceName: "Geotechnical Survey Team",
      totalScopeQty: 24,
      unit: "boreholes",
      targetDailyRate: 2,
      actualDailyRateAchieved: 2
    },
    earlyStart: "2026-02-02",
    earlyFinish: "2026-02-14",
    lateStart: "2026-02-02",
    lateFinish: "2026-02-14",
    totalFloat: 0,
    freeFloat: 0,
    isCritical: true,
    forecastStart: "2026-02-02",
    forecastFinish: "2026-02-14",
    varianceB0Days: 0,
    varianceB1Days: 0,
    responsiblePerson: "Survey Lead"
  },

  // 2.0 SUBSTRUCTURE & EARTHWORKS (CRITICAL PATH)
  {
    id: "act-201",
    wbsCode: "ACT-201",
    name: "Bulk Earthworks & Hard Rock Excavation (Piers P1-P4)",
    description: "Excavation through basalt strata with 45T heavy excavators and hydraulic breaker attachments",
    activityType: "Task",
    calendarId: "cal-6day",
    sortOrder: 4,
    originalDuration: 28,
    remainingDuration: 4,
    actualDuration: 30,
    progress: 88,
    status: "In Progress",
    actualStart: "2026-02-16",
    constraintType: "ASAP",
    predecessors: [
      { id: "p-201-1", predecessorId: "act-102", type: "FS", lag: 0 }
    ],
    successors: [],
    baseline0: { baselineStart: "2026-02-16", baselineFinish: "2026-03-20", duration: 28, scopeQty: 18500 },
    baseline1: { baselineStart: "2026-02-16", baselineFinish: "2026-03-24", duration: 32, scopeQty: 18500 },
    resourceAssignment: {
      resourceId: "res-earthworks",
      resourceName: "Heavy Earthworks Staff Team #1",
      totalScopeQty: 18500,
      unit: "m³",
      targetDailyRate: 660,
      actualDailyRateAchieved: 540
    },
    earlyStart: "2026-02-16",
    earlyFinish: "2026-03-25",
    lateStart: "2026-02-16",
    lateFinish: "2026-03-25",
    totalFloat: 0,
    freeFloat: 0,
    isCritical: true,
    forecastStart: "2026-02-16",
    forecastFinish: "2026-03-28",
    varianceB0Days: 8,
    varianceB1Days: 4,
    responsiblePerson: "Earthworks Subcontractor"
  },
  {
    id: "act-202",
    wbsCode: "ACT-202",
    name: "Rotary Bored Piling (900mm dia. x 22m Depth)",
    description: "48 continuous flight auger / rotary bored cast-in-situ piles with polymer slurry support",
    activityType: "Task",
    calendarId: "cal-6day",
    sortOrder: 5,
    originalDuration: 24,
    remainingDuration: 18,
    actualDuration: 8,
    progress: 35,
    status: "In Progress",
    actualStart: "2026-03-02",
    constraintType: "ASAP",
    predecessors: [
      // SS + 12 days lag relationship with Bulk Earthworks!
      { id: "p-202-1", predecessorId: "act-201", type: "SS", lag: 12 }
    ],
    successors: [],
    baseline0: { baselineStart: "2026-03-02", baselineFinish: "2026-03-28", duration: 24, scopeQty: 48 },
    baseline1: { baselineStart: "2026-03-02", baselineFinish: "2026-04-02", duration: 27, scopeQty: 48 },
    resourceAssignment: {
      resourceId: "res-piling",
      resourceName: "Bauer BG-36 Rotary Piling Rig",
      totalScopeQty: 48,
      unit: "piles",
      targetDailyRate: 2,
      actualDailyRateAchieved: 1.6
    },
    earlyStart: "2026-03-02",
    earlyFinish: "2026-04-04",
    lateStart: "2026-03-02",
    lateFinish: "2026-04-04",
    totalFloat: 0,
    freeFloat: 0,
    isCritical: true,
    forecastStart: "2026-03-02",
    forecastFinish: "2026-04-07",
    varianceB0Days: 10,
    varianceB1Days: 5,
    responsiblePerson: "Specialist Piling Contractor"
  },
  {
    id: "act-203",
    wbsCode: "ACT-203",
    name: "Pile Head Cropping & Sonic Integrity Testing (CSIT)",
    description: "Hydraulic pile cropping down to cutoff level, debonding rebar, and crosshole ultrasonic sonic logging",
    activityType: "Task",
    calendarId: "cal-6day",
    sortOrder: 6,
    originalDuration: 8,
    remainingDuration: 8,
    actualDuration: 0,
    progress: 0,
    status: "Not Started",
    constraintType: "ASAP",
    predecessors: [
      { id: "p-203-1", predecessorId: "act-202", type: "FF", lag: 2 }
    ],
    successors: [],
    baseline0: { baselineStart: "2026-03-24", baselineFinish: "2026-04-01", duration: 8, scopeQty: 48 },
    baseline1: { baselineStart: "2026-03-28", baselineFinish: "2026-04-06", duration: 8, scopeQty: 48 },
    resourceAssignment: {
      resourceId: "res-testing",
      resourceName: "NDT Quality Testing Unit",
      totalScopeQty: 48,
      unit: "piles",
      targetDailyRate: 6,
      actualDailyRateAchieved: 0
    },
    earlyStart: "2026-03-30",
    earlyFinish: "2026-04-08",
    lateStart: "2026-03-30",
    lateFinish: "2026-04-08",
    totalFloat: 0,
    freeFloat: 0,
    isCritical: true,
    forecastStart: "2026-04-02",
    forecastFinish: "2026-04-11",
    varianceB0Days: 10,
    varianceB1Days: 5,
    responsiblePerson: "Independent Testing Agency"
  },
  {
    id: "act-204",
    wbsCode: "ACT-204",
    name: "Reinforced Concrete Pile Caps & Ground Beams (C40/50)",
    description: "Shuttering, rebar fixing (high yield steel 460B), and monolithic concrete pour with superplasticizer",
    activityType: "Task",
    calendarId: "cal-7day", // 7-day continuous curing
    sortOrder: 7,
    originalDuration: 18,
    remainingDuration: 18,
    actualDuration: 0,
    progress: 0,
    status: "Not Started",
    constraintType: "ASAP",
    predecessors: [
      { id: "p-204-1", predecessorId: "act-203", type: "FS", lag: 0 }
    ],
    successors: [],
    baseline0: { baselineStart: "2026-04-02", baselineFinish: "2026-04-19", duration: 18, scopeQty: 2400 },
    baseline1: { baselineStart: "2026-04-07", baselineFinish: "2026-04-24", duration: 18, scopeQty: 2400 },
    resourceAssignment: {
      resourceId: "res-concrete",
      resourceName: "Concrete Placement & Formwork Staff Team",
      totalScopeQty: 2400,
      unit: "m³",
      targetDailyRate: 140,
      actualDailyRateAchieved: 0
    },
    earlyStart: "2026-04-09",
    earlyFinish: "2026-04-26",
    lateStart: "2026-04-09",
    lateFinish: "2026-04-26",
    totalFloat: 0,
    freeFloat: 0,
    isCritical: true,
    forecastStart: "2026-04-12",
    forecastFinish: "2026-04-29",
    varianceB0Days: 10,
    varianceB1Days: 5,
    responsiblePerson: "Structural Civils Lead"
  },
  {
    id: "act-205",
    wbsCode: "M-020",
    name: "Key Milestone: Substructure Practical Handover",
    description: "Inspection of all foundation caps and sign-off by Resident Engineer under FIDIC Clause 10.1",
    activityType: "FinishMilestone",
    calendarId: "cal-5day",
    sortOrder: 8,
    originalDuration: 0,
    remainingDuration: 0,
    actualDuration: 0,
    progress: 0,
    status: "Not Started",
    constraintType: "ASAP",
    predecessors: [
      { id: "p-205-1", predecessorId: "act-204", type: "FS", lag: 0 }
    ],
    successors: [],
    baseline0: { baselineStart: "2026-04-20", baselineFinish: "2026-04-20", duration: 0 },
    baseline1: { baselineStart: "2026-04-25", baselineFinish: "2026-04-25", duration: 0 },
    earlyStart: "2026-04-27",
    earlyFinish: "2026-04-27",
    lateStart: "2026-04-27",
    lateFinish: "2026-04-27",
    totalFloat: 0,
    freeFloat: 0,
    isCritical: true,
    forecastStart: "2026-04-30",
    forecastFinish: "2026-04-30",
    varianceB0Days: 10,
    varianceB1Days: 5,
    responsiblePerson: "Resident Engineer"
  },

  // 3.0 SUPERSTRUCTURE & BRIDGE DECK (CRITICAL PATH)
  {
    id: "act-301",
    wbsCode: "ACT-301",
    name: "Precast Concrete Superstructure Pier Columns (P1-P8)",
    description: "Erection of 8m precast hollow pier columns with internal post-tensioning anchorages",
    activityType: "Task",
    calendarId: "cal-6day",
    sortOrder: 9,
    originalDuration: 22,
    remainingDuration: 22,
    actualDuration: 0,
    progress: 0,
    status: "Not Started",
    constraintType: "ASAP",
    predecessors: [
      { id: "p-301-1", predecessorId: "act-205", type: "FS", lag: 0 }
    ],
    successors: [],
    baseline0: { baselineStart: "2026-04-21", baselineFinish: "2026-05-16", duration: 22, scopeQty: 16 },
    baseline1: { baselineStart: "2026-04-26", baselineFinish: "2026-05-21", duration: 22, scopeQty: 16 },
    resourceAssignment: {
      resourceId: "res-crane",
      resourceName: "250T Mobile Crawler Crane & Rigging Team",
      totalScopeQty: 16,
      unit: "columns",
      targetDailyRate: 0.8,
      actualDailyRateAchieved: 0
    },
    earlyStart: "2026-04-28",
    earlyFinish: "2026-05-23",
    lateStart: "2026-04-28",
    lateFinish: "2026-05-23",
    totalFloat: 0,
    freeFloat: 0,
    isCritical: true,
    forecastStart: "2026-05-01",
    forecastFinish: "2026-05-27",
    varianceB0Days: 11,
    varianceB1Days: 6,
    responsiblePerson: "Heavy Rigging Contractor"
  },
  {
    id: "act-302",
    wbsCode: "ACT-302",
    name: "Structural Steel Box Girder Deck Erection & Splice Bolting",
    description: "Heavy lifting of 45m span weathering steel box girders with high-strength friction grip (HSFG) bolts",
    activityType: "Task",
    calendarId: "cal-6day",
    sortOrder: 10,
    originalDuration: 30,
    remainingDuration: 30,
    actualDuration: 0,
    progress: 0,
    status: "Not Started",
    constraintType: "ASAP",
    predecessors: [
      // SS with pier erection + 10 days lag
      { id: "p-302-1", predecessorId: "act-301", type: "SS", lag: 10 }
    ],
    successors: [],
    baseline0: { baselineStart: "2026-05-04", baselineFinish: "2026-06-08", duration: 30, scopeQty: 1250 },
    baseline1: { baselineStart: "2026-05-09", baselineFinish: "2026-06-13", duration: 30, scopeQty: 1250 },
    resourceAssignment: {
      resourceId: "res-steel",
      resourceName: "Structural Steel Erection Crew",
      totalScopeQty: 1250,
      unit: "tons",
      targetDailyRate: 42,
      actualDailyRateAchieved: 0
    },
    earlyStart: "2026-05-11",
    earlyFinish: "2026-06-15",
    lateStart: "2026-05-11",
    lateFinish: "2026-06-15",
    totalFloat: 0,
    freeFloat: 0,
    isCritical: true,
    forecastStart: "2026-05-14",
    forecastFinish: "2026-06-19",
    varianceB0Days: 11,
    varianceB1Days: 6,
    responsiblePerson: "Steelwork Fabricator"
  },
  {
    id: "act-303",
    wbsCode: "ACT-303",
    name: "In-Situ Deck Slab Concreting & Post-Tensioned Stressing",
    description: "Composite concrete deck slab placement and multi-strand tendon stressing to 1450 kN per duct",
    activityType: "Task",
    calendarId: "cal-7day",
    sortOrder: 11,
    originalDuration: 20,
    remainingDuration: 20,
    actualDuration: 0,
    progress: 0,
    status: "Not Started",
    constraintType: "ASAP",
    predecessors: [
      { id: "p-303-1", predecessorId: "act-302", type: "FS", lag: 0 }
    ],
    successors: [],
    baseline0: { baselineStart: "2026-06-09", baselineFinish: "2026-06-28", duration: 20, scopeQty: 3200 },
    baseline1: { baselineStart: "2026-06-14", baselineFinish: "2026-07-03", duration: 20, scopeQty: 3200 },
    resourceAssignment: {
      resourceId: "res-deck",
      resourceName: "Deck Concreting & PT Team",
      totalScopeQty: 3200,
      unit: "m³",
      targetDailyRate: 160,
      actualDailyRateAchieved: 0
    },
    earlyStart: "2026-06-16",
    earlyFinish: "2026-07-05",
    lateStart: "2026-06-16",
    lateFinish: "2026-07-05",
    totalFloat: 0,
    freeFloat: 0,
    isCritical: true,
    forecastStart: "2026-06-20",
    forecastFinish: "2026-07-09",
    varianceB0Days: 11,
    varianceB1Days: 6,
    responsiblePerson: "Bridge Specialist"
  },

  // 4.0 SECONDARY SYSTEMS (NON-CRITICAL WITH FLOAT)
  {
    id: "act-401",
    wbsCode: "ACT-401",
    name: "Bridge Parapets, Expansion Joints & Waterproof Membrane",
    description: "Class H4a high-containment steel vehicle parapets and spray-applied elastomeric waterproofing",
    activityType: "Task",
    calendarId: "cal-6day",
    sortOrder: 12,
    originalDuration: 14,
    remainingDuration: 14,
    actualDuration: 0,
    progress: 0,
    status: "Not Started",
    constraintType: "ASAP",
    predecessors: [
      { id: "p-401-1", predecessorId: "act-303", type: "FS", lag: 0 }
    ],
    successors: [],
    baseline0: { baselineStart: "2026-06-29", baselineFinish: "2026-07-15", duration: 14, scopeQty: 720 },
    baseline1: { baselineStart: "2026-07-04", baselineFinish: "2026-07-20", duration: 14, scopeQty: 720 },
    resourceAssignment: {
      resourceId: "res-fitout",
      resourceName: "Parapet & Surfacing Crew",
      totalScopeQty: 720,
      unit: "lin.m",
      targetDailyRate: 52,
      actualDailyRateAchieved: 0
    },
    earlyStart: "2026-07-06",
    earlyFinish: "2026-07-21",
    lateStart: "2026-07-14",
    lateFinish: "2026-07-29",
    totalFloat: 8,
    freeFloat: 8,
    isCritical: false,
    forecastStart: "2026-07-10",
    forecastFinish: "2026-07-25",
    varianceB0Days: 10,
    varianceB1Days: 5,
    responsiblePerson: "Specialist Subcontractor"
  },
  {
    id: "act-402",
    wbsCode: "ACT-402",
    name: "Architectural Cladding & Acoustic Noise Barrier Installation",
    description: "Perforated aluminium sound absorption panels along rail boundaries",
    activityType: "Task",
    calendarId: "cal-6day",
    sortOrder: 13,
    originalDuration: 16,
    remainingDuration: 16,
    actualDuration: 0,
    progress: 0,
    status: "Not Started",
    constraintType: "ASAP",
    predecessors: [
      { id: "p-402-1", predecessorId: "act-303", type: "FS", lag: 2 }
    ],
    successors: [],
    baseline0: { baselineStart: "2026-07-01", baselineFinish: "2026-07-20", duration: 16, scopeQty: 1400 },
    baseline1: { baselineStart: "2026-07-06", baselineFinish: "2026-07-25", duration: 16, scopeQty: 1400 },
    resourceAssignment: {
      resourceId: "res-acoustic",
      resourceName: "Acoustic Wall Specialist",
      totalScopeQty: 1400,
      unit: "m²",
      targetDailyRate: 90,
      actualDailyRateAchieved: 0
    },
    earlyStart: "2026-07-08",
    earlyFinish: "2026-07-25",
    lateStart: "2026-07-12",
    lateFinish: "2026-07-29",
    totalFloat: 4,
    freeFloat: 4,
    isCritical: false,
    forecastStart: "2026-07-12",
    forecastFinish: "2026-07-29",
    varianceB0Days: 9,
    varianceB1Days: 4,
    responsiblePerson: "Architectural Lead"
  },

  // 5.0 INTEGRATED TESTING, COMMISSIONING & COMPLETION
  {
    id: "act-501",
    wbsCode: "ACT-501",
    name: "Track Geometry, Overhead Traction & Signalling Live Integration",
    description: "Catenary electrification energisation, track gauge alignment, and interlocking safety testing",
    activityType: "Task",
    calendarId: "cal-6day",
    sortOrder: 14,
    originalDuration: 14,
    remainingDuration: 14,
    actualDuration: 0,
    progress: 0,
    status: "Not Started",
    constraintType: "ASAP",
    predecessors: [
      { id: "p-501-1", predecessorId: "act-303", type: "FS", lag: 0 },
      { id: "p-501-2", predecessorId: "act-401", type: "FF", lag: 0 }
    ],
    successors: [],
    baseline0: { baselineStart: "2026-07-06", baselineFinish: "2026-07-21", duration: 14, scopeQty: 1 },
    baseline1: { baselineStart: "2026-07-11", baselineFinish: "2026-07-26", duration: 14, scopeQty: 1 },
    resourceAssignment: {
      resourceId: "res-mep",
      resourceName: "Rail Systems & MEP Integration Team",
      totalScopeQty: 1,
      unit: "system",
      targetDailyRate: 0.07,
      actualDailyRateAchieved: 0
    },
    earlyStart: "2026-07-22",
    earlyFinish: "2026-08-06",
    lateStart: "2026-07-22",
    lateFinish: "2026-08-06",
    totalFloat: 0,
    freeFloat: 0,
    isCritical: true,
    forecastStart: "2026-07-26",
    forecastFinish: "2026-08-10",
    varianceB0Days: 20,
    varianceB1Days: 15,
    responsiblePerson: "Systems Director"
  },
  {
    id: "act-502",
    wbsCode: "M-050",
    name: "Contractual Sectional Handover & Taking-Over Certificate (TOC)",
    description: "Final client inspection, issuance of Taking-Over Certificate under FIDIC Yellow/Red Book Clause 10",
    activityType: "FinishMilestone",
    calendarId: "cal-5day",
    sortOrder: 15,
    originalDuration: 0,
    remainingDuration: 0,
    actualDuration: 0,
    progress: 0,
    status: "Not Started",
    constraintType: "ASAP",
    predecessors: [
      { id: "p-502-1", predecessorId: "act-501", type: "FS", lag: 0 },
      { id: "p-502-2", predecessorId: "act-402", type: "FS", lag: 0 }
    ],
    successors: [],
    baseline0: { baselineStart: "2026-07-22", baselineFinish: "2026-07-22", duration: 0 },
    baseline1: { baselineStart: "2026-07-27", baselineFinish: "2026-07-27", duration: 0 },
    earlyStart: "2026-08-07",
    earlyFinish: "2026-08-07",
    lateStart: "2026-08-07",
    lateFinish: "2026-08-07",
    totalFloat: 0,
    freeFloat: 0,
    isCritical: true,
    forecastStart: "2026-08-11",
    forecastFinish: "2026-08-11",
    varianceB0Days: 20,
    varianceB1Days: 15,
    responsiblePerson: "Project Director / FIDIC Engineer"
  }
];
